I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 66, in script
    angel "Anyway! Let me introduce myself. I’m *[insert name + dramatic title]*!"
KeyError: 'insert name + dramatic title'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 66, in script
    angel "Anyway! Let me introduce myself. I’m *[insert name + dramatic title]*!"
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\character.py", line 1337, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\character.py", line 1251, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\character.py", line 1231, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 165, in vformat
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 205, in _vformat
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 270, in get_field
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 227, in get_value
KeyError: 'insert name + dramatic title'

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
a_day_for_the_dead 1.0
Fri May 16 10:55:35 2025
